[project]
name = "evo-widgets"
description = "Modern anywidget-based Jupyter widgets for Seequent Evo SDK"
version = "0.1.0"
requires-python = ">=3.10"
license-files = ["LICENSE.md"]
dynamic = ["readme"]
authors = [
    { name = "Seequent", email = "support@seequent.com" }
]

dependencies = [
    "evo-sdk-common[aiohttp]",
    "anywidget>=0.9",
    "traitlets>=5.0",
    "python-dotenv",
]

[project.urls]
Source = "https://github.com/SeequentEvo/evo-python-sdk"
Tracker = "https://github.com/SeequentEvo/evo-python-sdk/issues"
Homepage = "https://www.seequent.com/"
Documentation = "https://developer.seequent.com/"

[project.optional-dependencies]
notebooks = [
    "ipykernel",
    "ipython",
]

[dependency-groups]
test = [
    "evo-widgets[notebooks]",
    "pytest",
    "pytest-playwright",
    "nbconvert",
]
dev = [
    "evo-widgets[notebooks]",
    "bumpver",
    "coverage[toml]",
    "ruff==0.14.0",
    "pre-commit",
    {include-group="test"},
]

[tool.ruff]
src = ["src", "tests"]
line-length = 120

[tool.ruff.lint]
extend-select = ["I", "RUF022"]

[build-system]
requires = ["hatchling", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/evo"]
artifacts = ["src/evo/widgets/static/*"]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"
